---
title: "p8105_hw6_zl2860"
author: "Zongchao Liu"
date: "11/16/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(modelr)
library(purrr)
library(patchwork)
```

# Load data
```{r}
set.seed(886)
birthweight = read_csv('./data/birthweight.csv')
skimr::skim(birthweight)
birthweight =
  birthweight %>%
  mutate(babysex = factor(babysex),
         frace = factor(frace),
         malform = factor(malform),
         mrace = factor(mrace)
         )
```

```{r}
# select features
step(lm(bwt ~ ., data = birthweight), direction = "both")

fit_bw_selected =
  lm(bwt ~ babysex + bhead + blength +delwt +fincome
     + gaweeks + mheight + mrace + parity +
       ppwt + smoken, data = birthweight)
summary(fit_bw_selected)

birthweight %>%
  add_predictions(fit_bw_selected) %>%
  add_residuals(fit_bw_selected) %>%
  ggplot(aes( x = pred, y = resid ) ) +
  geom_point(alpha = .4) +
  theme_bw() +
  labs(title = " Residual vs Fitted Values") +
  theme(plot.title = element_text(hjust =.5)) +
  geom_line(aes(y = 0), color = "blue")
  
  
  
```

```{r}
fit_main = lm(bwt ~ gaweeks ,data = birthweight)
fit_inter = lm(bwt ~ bhead * blength * babysex ,data = birthweight)
summary(fit_main)
summary(fit_inter)
```

```{r}
cv_df = 
  crossv_mc(birthweight,1000) %>%
  mutate(train = map(train, as_tibble),
         test = map (test, as_tibble),
         model_selected = map(train, ~lm(bwt ~ babysex + bhead + blength +delwt +fincome + gaweeks + mheight + mrace + parity + ppwt + smoken, data = .x)),
         model_main = map(train, ~lm(bwt ~ gaweeks , data = .x)),
         model_inter = map(train,~lm(bwt ~ bhead * blength * babysex , data = .x)),
         ) %>%
  mutate(rmse_main = map2_dbl(model_main, test, ~rmse(model = .x, data = .y)),
         rmse_inter = map2_dbl(model_inter, test, ~rmse(model = .x, data = .y)),
         rmse_selected = map2_dbl(model_selected, test, ~rmse(model = .x, data =.y)))

cv_df %>%
  select(starts_with("rmse")) %>%
  pivot_longer(everything(),
               names_to = "model",
               values_to = "rmse",
               names_prefix = "rmse_") %>%
  ggplot(aes(x = model, y = rmse, fill = model)) +
  geom_violin() +
  ggsci::scale_fill_lancet() +
  theme_bw() +
  labs(title = "Model Comparison") +
  theme( plot.title = element_text(hjust = .5))



```

# Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Create a function for resampling data with replacement

```{r}
boot_sample = 
  function(df){
  sample_frac(df, replace = T)
  }

```

## Bootstrap

```{r}
#resample 5000 times
bootstrap_df = 
  tibble(
    sample_id = 1 : 5000,
    sample = rerun(5000,boot_sample(weather_df))
  )

# organize results
estimates =
  bootstrap_df %>%
  mutate(model = map(sample, ~lm(tmax ~ tmin, data = .x)),
         result_r = map(model, broom::glance),
         result_beta = map(model, broom::tidy)) %>%
  select(sample_id,result_r, result_beta) %>%
  unnest() %>%
  mutate(term = recode(term, 
                       "(Intercept)" = "beta_0",
                       "tmin" = "beta_1")) %>%
  janitor::clean_names() %>%
  select(sample_id, r_squared, adj_r_squared,term, estimate) %>%
  pivot_wider( names_from = term,
               values_from = estimate) %>%
  mutate(log_beta = log(beta_1 * beta_0))
```

## Plot the distributions 

```{r}
# distribution for beta
plt_beta =
  estimates %>%
  ggplot(aes( x = r_squared)) +
  geom_histogram(fill = "blue", alpha = .4) +
  geom_density() +
  theme_bw() +
  labs(title = "Distribution for log(β̂0β̂1)",
       x = "log(β̂0β̂1",
       y = " Count") +
  theme(plot.title = element_text(hjust = .5 ))

# distribution for r2
plt_rsq =
  estimates %>%
  ggplot(aes( x = log_beta)) +
  geom_histogram(fill = "red", alpha = .4) +
  theme_bw() +
  geom_density() +
  labs(title = "Distribution for r̂2",
       x = "r̂2",
       y = "Count") +
  theme(plot.title = element_text(hjust = .5 ))

plt_rsq + plt_beta

  

  
  
```

## 95% CI
```{r}
quantile(pull(estimates,log_beta), c(.25, .975))
```


